version: '3.8'

# Configuration pour déploiement serveur sans IP fixe
# Utilise les ports à partir de 10000

services:
  # ==================== SERVICE PRINCIPAL API/DASHBOARD ====================
  api-dashboard-service:
    build:
      context: ./api-dashboard-service
      dockerfile: Dockerfile
    container_name: saas-api-dashboard
    ports:
      - "10000:8000"  # Dashboard principal sur port 10000
    environment:
      - DATABASE_URL=postgresql://warehouse_user:warehouse_password@warehouse-service:5432/data_warehouse
      - NIFI_SERVICE_URL=http://nifi-service:8080
      - DBT_SERVICE_URL=http://dbt-service:8001
      - RECONCILIATION_SERVICE_URL=http://reconciliation-service:8002
      - QUALITY_CONTROL_SERVICE_URL=http://quality-control-service:8003
      - RCA_SERVICE_URL=http://rca-service:8004
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      - warehouse-service
    networks:
      - saas-network
    volumes:
      - ./api-dashboard-service/app:/app
      - dashboard-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== SERVICE NIFI POUR INGESTION ====================
  nifi-service:
    build:
      context: ./nifi-service
      dockerfile: Dockerfile
    container_name: saas-nifi
    ports:
      - "10080:8080"  # NiFi sur port 10080
      - "9443:8443"
      - "9100:10000"
      - "9800:8000"
    environment:
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_SENSITIVE_PROPS_KEY=
    networks:
      - saas-network
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-database:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi-logs:/opt/nifi/nifi-current/logs
      - nifi-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nifi/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== SERVICE DBT POUR TRANSFORMATION ====================
  dbt-service:
    build:
      context: ./dbt-service
      dockerfile: Dockerfile
    container_name: saas-dbt
    ports:
      - "10001:8001"  # DBT service sur port 10001
    environment:
      - DATABASE_URL=postgresql://warehouse_user:warehouse_password@warehouse-service:5432/data_warehouse
      - PYTHONPATH=/app
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      - warehouse-service
    networks:
      - saas-network
    volumes:
      - ./dbt-service/app:/app
      - dbt-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== SERVICE RÉCONCILIATION ZINGG ====================
  reconciliation-service:
    build:
      context: ./reconciliation-service
      dockerfile: Dockerfile
    container_name: saas-reconciliation
    ports:
      - "10002:8002"  # Réconciliation sur port 10002
    environment:
      - DATABASE_URL=postgresql://warehouse_user:warehouse_password@warehouse-service:5432/data_warehouse
      - PYTHONPATH=/app
      - ZINGG_WORKSPACE=/tmp/zingg_workspace
      - ZINGG_MODEL_PATH=/tmp/zingg_models
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      - warehouse-service
    networks:
      - saas-network
    volumes:
      - ./reconciliation-service/app:/app
      - zingg-workspace:/tmp/zingg_workspace
      - zingg-models:/tmp/zingg_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== SERVICE CONTRÔLE QUALITÉ SODA ====================
  quality-control-service:
    build:
      context: ./quality-control-service
      dockerfile: Dockerfile
    container_name: saas-quality-control
    ports:
      - "10003:8003"  # Contrôle qualité sur port 10003
    environment:
      - DATABASE_URL=postgresql://warehouse_user:warehouse_password@warehouse-service:5432/data_warehouse
      - PYTHONPATH=/app
      - SODA_CONFIG_PATH=/app/soda_config
      - SODA_CHECKS_PATH=/app/soda_checks
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      - warehouse-service
    networks:
      - saas-network
    volumes:
      - ./quality-control-service/app:/app
      - soda-config:/app/soda_config
      - soda-checks:/app/soda_checks
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== SERVICE RCA POUR ANALYSE DES CAUSES RACINES ====================
  rca-service:
    build:
      context: ./rca-service
      dockerfile: Dockerfile
    container_name: saas-rca
    ports:
      - "10004:8004"  # RCA sur port 10004
    environment:
      - DATABASE_URL=postgresql://warehouse_user:warehouse_password@warehouse-service:5432/data_warehouse
      - PYTHONPATH=/app
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      - warehouse-service
    networks:
      - saas-network
    volumes:
      - ./rca-service/app:/app
      - rca-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==================== SERVICE WAREHOUSE POSTGRESQL ====================
  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile
    container_name: saas-warehouse
    ports:
      - "10543:5432"  # PostgreSQL sur port 10543
    environment:
      - POSTGRES_DB=data_warehouse
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    networks:
      - saas-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./warehouse-service/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse_user -d data_warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==================== REDIS POUR CACHE ET SESSIONS ====================
  redis:
    image: redis:7-alpine
    container_name: saas-redis
    ports:
      - "10637:6379"  # Redis sur port 10637
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - saas-network
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==================== NGINX POUR REVERSE PROXY ====================
  nginx:
    image: nginx:alpine
    container_name: saas-nginx
    ports:
      - "80:80"      # HTTP sur port 80
      - "443:443"    # HTTPS sur port 443
    volumes:
      - ./nginx/nginx.server.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-dashboard-service
      - nifi-service
    networks:
      - saas-network
    restart: unless-stopped

  # ==================== PROMETHEUS POUR MONITORING ====================
  prometheus:
    image: prom/prometheus:latest
    container_name: saas-prometheus
    ports:
      - "10090:9090"  # Prometheus sur port 10090
    volumes:
      - ./monitoring/prometheus.server.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - saas-network
    restart: unless-stopped

  # ==================== GRAFANA POUR VISUALISATION ====================
  grafana:
    image: grafana/grafana:latest
    container_name: saas-grafana
    ports:
      - "10300:3000"  # Grafana sur port 10300
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:10300/
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    networks:
      - saas-network
    restart: unless-stopped

  # ==================== KAFKA POUR STREAMING (OPTIONNEL) ====================
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: saas-zookeeper
    ports:
      - "10218:2181"  # Zookeeper sur port 10218
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - saas-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: saas-kafka
    ports:
      - "10092:9092"  # Kafka sur port 10092 (standard)
      - "10093:9093"  # Kafka alternatif sur port 10093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:10092,PLAINTEXT_HOST://localhost:10093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - saas-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

  # ==================== MINIO POUR STOCKAGE OBJET (OPTIONNEL) ====================
  minio:
    image: minio/minio:latest
    container_name: saas-minio
    ports:
      - "10900:9000"  # MinIO API sur port 10900 (évite le conflit)
      - "10901:9001"  # MinIO Console sur port 10901
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    networks:
      - saas-network
    volumes:
      - minio-data:/data
    restart: unless-stopped

# ==================== RÉSEAUX ====================
networks:
  saas-network:
    driver: bridge
    # Configuration ipam commentée pour éviter les conflits de sous-réseau
    # Docker choisira automatiquement un sous-réseau disponible
    # ipam:
    #   config:
    #     - subnet: 172.25.0.0/16

# ==================== VOLUMES PERSISTANTS ====================
volumes:
  # Volumes PostgreSQL
  postgres-data:
    driver: local
  
  # Volumes NiFi
  nifi-conf:
    driver: local
  nifi-database:
    driver: local
  nifi-flowfile:
    driver: local
  nifi-content:
    driver: local
  nifi-provenance:
    driver: local
  nifi-logs:
    driver: local
  nifi-data:
    driver: local
  
  # Volumes des services
  dbt-data:
    driver: local
  zingg-workspace:
    driver: local
  zingg-models:
    driver: local
  soda-config:
    driver: local
  soda-checks:
    driver: local
  rca-data:
    driver: local
  dashboard-data:
    driver: local
  
  # Volumes Redis
  redis-data:
    driver: local
  
  # Volumes monitoring
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  
  # Volumes streaming
  kafka-data:
    driver: local
  
  # Volumes stockage objet
  minio-data:
    driver: local
